// <auto-generated />
using System;
using Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    [Migration("20180608133021_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("Inventory.Inventory.InventoryMaster", b =>
                {
                    b.Property<Guid>("AggregateRootId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GeneralNomenclature");

                    b.Property<int>("Id");

                    b.Property<bool>("IsGArmy");

                    b.Property<string>("LIN");

                    b.Property<int>("Status");

                    b.Property<int>("TrackingType");

                    b.HasKey("AggregateRootId");

                    b.ToTable("InventoryMasters");
                });

            modelBuilder.Entity("Isf.Core.Cqrs.DomainEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AggregateRootId");

                    b.Property<string>("EventData");

                    b.Property<string>("EventName");

                    b.Property<int>("EventSequence");

                    b.Property<DateTime>("EventTimestamp");

                    b.Property<string>("UserCreated");

                    b.HasKey("EventId");

                    b.ToTable("DomainEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
