// <auto-generated />
using Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(DomainDbContext))]
    partial class DomainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Inventory.Inventory.InventoryMaster", b =>
                {
                    b.Property<Guid>("AggregateRootId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("GeneralNomenclature");

                    b.Property<int>("Id");

                    b.Property<bool>("IsGArmy");

                    b.Property<string>("LIN");

                    b.Property<int>("Status");

                    b.Property<int>("TrackingType");

                    b.HasKey("AggregateRootId");

                    b.ToTable("InventoryMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
